AUTHOR = 'Valentín Giménez'
SITENAME = 'Portfolio'
SITEURL = ''
PATH = 'content'
TIMEZONE = 'America/Argentina/Buenos_Aires'
DEFAULT_LANG = 'es'
DEFAULT_DATE_FORMAT = '%d-%m-%Y'
STATIC_PATHS = ['images', 'cv_valentin_gimenez.pdf']
THEME = 'themes/Flex'  # Deberás clonar el tema manualmente en esta carpeta
